#!/usr/bin/env bash
# Runs Nginx as the main nginx user while listening on port 8080.

# set a user in the config by replace '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# This line changes port 80 with 8080 /sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give file permissions of read and write to the configuration file
chmod 644 /etc/nginx/nginx.conf

# Kill any process id which will prevent nginx to run on port 80
pkill apache2

# Start the nginx service with the nginx user
sudo -u nginx service nginx start
